name: Build the project and run tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive   

      - name: Install Dependencies
        run: |
          sudo apt install -y build-essential python-is-python3

      - name: Build the Project
        run: make

      - name: Run Unit Tests
        run: python3 unit_tests.py
